{
 "title": "postgres test-2",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "category",
    "query": "SELECT distinct categories FROM expenses"
   },
   {
    "name": "maxCost",
    "query": "1000, 5000, 10000, 50000, 500000"
   }
  ]
 },
 "panels": [
  {
   "title": "Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total cost",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  NOW() AS \"time\",\n  sum(cost),\n  'over all time' AS metric\nFROM expenses"
      },
      {
       "rawSql": "SELECT\n  NOW() AS \"time\",\n  sum(cost),\n  'in range' AS metric\nFROM expenses\nwhere  $__timeFilter(occured_at)\n"
      }
     ]
    },
    {
     "title": "Average cost",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  NOW() AS \"time\",\n  sum(cost) / count(id),\n  'over all time' AS metric\nFROM expenses"
      },
      {
       "rawSql": "SELECT\n  NOW() AS \"time\",\n  sum(cost) / count(id),\n  'in range' AS metric\nFROM expenses\nwhere  $__timeFilter(occured_at)"
      }
     ]
    },
    {
     "title": "Amount of transaction",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  NOW() AS \"time\",\n  count(id),\n  'over all time' as metric\nFROM expenses"
      },
      {
       "rawSql": "SELECT\n  NOW() AS \"time\",\n  count(id),\n  'in range' as metric\nFROM expenses\nwhere  $__timeFilter(occured_at)"
      }
     ]
    },
    {
     "title": "Cost <= 5000 ",
     "type": "histogram",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "rawSql": "SELECT\n  occured_at AS \"time\",\n  cost,\n  'Over all time' as metric\nFROM expenses\nWHERE\n  cost <= 5000\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  occured_at AS \"time\",\n  cost,\n  'In range' as metric\nFROM expenses\nWHERE\n$__timeFilter(occured_at) AND\n  cost <= 5000\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Cost  > 5000 ",
     "type": "histogram",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "rawSql": "SELECT\n  occured_at AS \"time\",\n  cost,\n  'Over all time' as metric\nFROM expenses\nWHERE\n  cost > 5000\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  occured_at AS \"time\",\n  cost,\n  'In range' as metric\nFROM expenses\nWHERE\n  $__timeFilter(occured_at) AND\n  cost > 5000\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "By time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Daily expenses total",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 16, "x": 0, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT sum(cost), $__timeGroup(occured_at,'1d', 0) AS time\nFROM expenses\nwhere  $__timeFilter(occured_at)\ngroup by time\nORDER BY 2\n"
      },
      {
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "Monthly expenses",
     "type": "barchart",
     "gridPos": { "h": 10, "w": 16, "x": 0, "y": 16 },
     "targets": [
      {
       "rawSql": "SELECT\n  NOW() as time,\n  sum(cost) AS value,\n  to_char(occured_at::date, 'YYYY MM/MONTH') AS metric\nFROM\n  expenses\nWHERE\n  $__timeFilter(occured_at)\nGROUP BY\n  metric\nORDER BY 3"
      }
     ]
    },
    {
     "title": "Annual expenses",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 16, "x": 0, "y": 26 },
     "targets": [
      {
       "rawSql": "SELECT\n  NOW() as time,\n  sum(cost) AS value,\n  to_char(occured_at::date, 'YYYY') AS metric\nFROM\n  expenses\nWHERE\n  $__timeFilter(occured_at)\nGROUP BY\n  metric\nORDER BY 3"
      }
     ]
    },
    {
     "title": "Category expenses",
     "type": "barchart",
     "gridPos": { "h": 32, "w": 22, "x": 0, "y": 35 },
     "targets": [
      {
       "rawSql": "SELECT\n  NOW() as time,\n  sum(cost) AS value,\n  categories AS metric\nFROM\n  expenses\nGROUP BY\n  metric\nORDER BY 3"
      },
      {
       "rawSql": "SELECT\n  NOW() as time,\n  sum(cost) AS value,\n  categories AS metric\nFROM\n  expenses\nWHERE\n  $__timeFilter(occured_at)\nGROUP BY\n  metric\nORDER BY 3"
      }
     ]
    }
   ]
  },
  {
   "title": "By categories and maxCost",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Daily expenses by categories=${category} and cost < $maxCost",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 16, "x": 0, "y": 3 },
     "targets": [
      {
       "rawSql": "SELECT sum(cost), $__timeGroup(occured_at,'1d', 0) AS time, categories as metric\nFROM expenses\nwhere  $__timeFilter(occured_at) AND categories IN ( ${category} ) AND cost < $maxCost\ngroup by time, categories\nORDER BY 2\n"
      }
     ]
    },
    {
     "title": "Monthly expenses  by categories=${category}",
     "type": "barchart",
     "gridPos": { "h": 21, "w": 16, "x": 0, "y": 17 },
     "targets": [
      {
       "rawSql": "SELECT\n  NOW() as time,\n  sum(cost) AS value,\n  CONCAT(to_char(occured_at::date, 'YYYY MM/MONTH'), ' ', categories) AS metric\nFROM\n  expenses\nWHERE\n  $__timeFilter(occured_at) AND categories IN ( ${category} )\nGROUP BY\n  metric, categories\nORDER BY 3"
      }
     ]
    },
    {
     "title": "Annual expenses  by categories=${category}",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 16, "x": 0, "y": 38 },
     "targets": [
      {
       "rawSql": "SELECT\n  NOW() as time,\n  sum(cost) AS value,\n  CONCAT(to_char(occured_at::date, 'YYYY'), ' ', categories) AS metric\nFROM\n  expenses\nWHERE\n  $__timeFilter(occured_at) AND categories IN ( ${category} )\nGROUP BY\n  metric\nORDER BY 3"
      }
     ]
    }
   ]
  }
 ]
}